/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const read_rksys: (a: any, b: number) => [number, number, number, number];
export const read_rkg: (a: any) => [number, number, number];
export const __wbg_rkg_free: (a: number, b: number) => void;
export const __wbg_get_rkg_track: (a: number) => number;
export const __wbg_set_rkg_track: (a: number, b: number) => void;
export const __wbg_get_rkg_time: (a: number) => number;
export const __wbg_set_rkg_time: (a: number, b: number) => void;
export const __wbg_get_rkg_combo: (a: number) => number;
export const __wbg_set_rkg_combo: (a: number, b: number) => void;
export const __wbg_get_rkg_controller: (a: number) => number;
export const __wbg_set_rkg_controller: (a: number, b: number) => void;
export const __wbg_get_rkg_year: (a: number) => number;
export const __wbg_set_rkg_year: (a: number, b: number) => void;
export const __wbg_get_rkg_month: (a: number) => number;
export const __wbg_set_rkg_month: (a: number, b: number) => void;
export const __wbg_get_rkg_day: (a: number) => number;
export const __wbg_set_rkg_day: (a: number, b: number) => void;
export const __wbg_get_rkg_miniturbo: (a: number) => number;
export const __wbg_set_rkg_miniturbo: (a: number, b: number) => void;
export const __wbg_get_rkg_lap1: (a: number) => number;
export const __wbg_set_rkg_lap1: (a: number, b: number) => void;
export const __wbg_get_rkg_lap2: (a: number) => number;
export const __wbg_set_rkg_lap2: (a: number, b: number) => void;
export const __wbg_get_rkg_lap3: (a: number) => number;
export const __wbg_set_rkg_lap3: (a: number, b: number) => void;
export const __wbg_get_rkg_shrooms: (a: number) => number;
export const __wbg_set_rkg_shrooms: (a: number, b: number) => void;
export const __wbg_shroomstrat_free: (a: number, b: number) => void;
export const __wbg_get_shroomstrat_shroomstrat: (a: number) => number;
export const __wbg_set_shroomstrat_shroomstrat: (a: number, b: number) => void;
export const __wbg_combo_free: (a: number, b: number) => void;
export const __wbg_get_combo_vehicle: (a: number) => number;
export const __wbg_set_combo_vehicle: (a: number, b: number) => void;
export const __wbg_get_combo_character: (a: number) => number;
export const __wbg_set_combo_character: (a: number, b: number) => void;
export const __wbindgen_export_0: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
